spring:
  profiles:
#    active: prod
    active: local
  data:
    web:
      pageable:
        default-page-size: 10
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  security:
    basic:
      enable: false

logging.level:
  org.hibernate.SQL: debug
